sudo: required
service:
  - docker

before_install:
  - docker build -t open2nix/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run open2nix/react-test npm test -- --coverage

after_success:
  - docker build -t open2nix/multi-client ./client
  - docker build -t open2nix/multi-nginx ./nginx
  - docker build -t open2nix/multi-server ./server
  - docker build -t open2nix/multi-worker ./worker
# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
  - docker push open2nix/multi-client
  - docker push open2nix/multi-nginx
  - docker push open2nix/multi-server
  - docker push open2nix/multi-worker